version: '3'

services:
  db:
    image: postgres:9.6
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    networks:
      - backend

  backend:
    build: './packages/server'
    environment:
      - DB_HOST=db
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@db:5432/city_bikes
    ports:
      - "3001:3001"
    depends_on:
      - db
    networks:
      - backend
    
  client:
    build: './packages/client'
    ports:
      - "3000:3000"
    networks:
      - backend
networks:
  backend:

