version: '3'

services:
  db:
    image: postgres:9.6
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"

  app:
    build: .
    environment:
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@db:5432/city-bikes
    ports:
      - "3000:3000"
    depends_on:
      - db
